In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1, 1], [12, 17, 22], [10, 17, 33]])
b = np.array([189, 3463, 4355])
x = np.linalg.solve(A, b)
x

array([38., 63., 88.])

In [3]:
import numpy as np
from numpy.linalg import linalg, inv

In [4]:
A = [[-2, -10, 3], [0, 1, 0], [-3, -14, 4]]
A = np.matrix(A)
print('\nMatrix A')
print(A)


Matrix A
[[ -2 -10   3]
 [  0   1   0]
 [ -3 -14   4]]


In [5]:
print('\nInverse of A')
IA = inv(A)
print(IA)


Inverse of A
[[ 4. -2. -3.]
 [ 0.  1.  0.]
 [ 3.  2. -2.]]
